set -g default-terminal "tmux-256color"
set -s escape-time 0

set pane-active-border-style fg=magenta
set pane-border-style fg=black
set-option -g status-position top

unbind C-b
set -g prefix C-e
bind C-e send-prefix

unbind %
unbind '"'
bind \\ split-window -h
bind - split-window -v

bind r source-file ~/.tmux.conf

bind -n M-j resize-pane -D 3
bind -n M-k resize-pane -U 3
bind -n M-l resize-pane -R 3
bind -n M-h resize-pane -L 3

set -g mouse on

bind m resize-pane -Z
bind t new-window

bind s display-popup -E "tms switch"
bind n display-popup -E "tms"
bind C-w display-popup -E "tms windows"

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

run '~/.tmux/plugins/tpm/tpm'
